<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

Subsetting means select some data in list or array
via Indexing,, selecting one element
or Slicing, which is a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [34]:
animallist = ["giraffe","monkey","kangeroo","dog","butterfly","otter","mice"]
animalarray = np.array(animallist)

x = animallist

x[0]

'giraffe'

In [5]:
x[-1]

'mice'

In [28]:
x[0:3]  # does NOT give u element w index 3 !!!
        # 3-0 elements starting from index 0

['giraffe', 'monkey', 'kangeroo']

In [31]:
x[1:3] # 3-1 so 1 element starting from index 1

['monkey', 'kangeroo']

In [29]:
x[5:] # index 5 to end

['otter', 'mice']

In [30]:
x[:5] # index 5 and before

['giraffe', 'monkey', 'kangeroo', 'dog', 'butterfly']

In [32]:
x[1:6:2] # 6-1 so 5 elements, index 1 to 5
         # in steps of 2

['monkey', 'dog', 'otter']

In [42]:
x[2:4:-1] # -1 at the end means reverse the list,
          # but the first 2 also needs to be reversed
x[4:1:-1] # 4-1 is 3 elements, from index 4 to 2 (not 1 to 3)

['butterfly', 'dog', 'kangeroo']

In [45]:
x[:-1]   # excludes the last element

['giraffe', 'monkey', 'kangeroo', 'dog', 'butterfly', 'otter']

In [37]:
x[::-1] # reverses list

['mice', 'otter', 'butterfly', 'dog', 'kangeroo', 'monkey', 'giraffe']

## 1.2 Arrays only | Subsetting by masking

In [2]:
numberarray = np.array([1,2,3,4,5,6,7,8,9,10])
masking = numberarray > 3
masking

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [3]:
numberarray[masking]

# masking only works for numpy arrays, you cant ask a list if its
# > 3, < 5 etc

array([ 4,  5,  6,  7,  8,  9, 10])

In [26]:
numberarray[~(masking)] # inverse the masking w the ~ not operator
# can combine one mask and another mask
# numerarray[masking] is the same as numberarray[numberarray>3]

numberarray[(numberarray>2) & (numberarray<8)]

# can comebine one mask or another mask 

numberarray[(numberarray<3)|(numberarray>8)] # | means or 

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [7]:
tdlist = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
tdarray = np.array(tdlist)

In [28]:
tdlist[3]
tdlist[3][1]
tdlist[3,1] # will not work

TypeError: list indices must be integers or slices, not tuple

In [14]:
# slicing lists
tdlist[:3] 

[[1, 'A'], [2, 'B'], [3, 'C']]

In [11]:
# arrays
tdarray[3]
tdarray[3][1]
tdarray[3,1]  # for arrays, u can index using [3,1] also

'D'

In [15]:
# slicing arrays
tdarray[:3] # element at index 0 to 2

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [17]:
tdarray[:3][0] # take the first 3 elements of the array, and then first element
# refer ontop
# same for lists

array(['1', 'A'], dtype='<U21')

In [31]:
# however, if you want to get the first element of each sublist
# like for [1,"A"],[2,"B"],[3,"C"]
# u want ([1,2,3])

print(tdarray[:3,0])

# for 'everything', just use :
tdarray[:,1] # first index (the alphabets) of all the elements (the sublists)
            # in the array

['1' '2' '3']


array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

## 1.4 Growing lists

In [32]:
x = [1,2]*4
x

[1, 2, 1, 2, 1, 2, 1, 2]

In [59]:
x = [1]
x += [2] # same as x = x + 2
x += [3]
x

x = [3] # must be a list initially
x = x + [2]
x = x + [4]
x

[3, 2, 4]

In [51]:
# x = 1 # will not work cuz this is integer, not any storage
x = [1]
x.append(4) # can use listname.append()
x

arrayy = np.array([1,2,3])
arrayy.append(4)
arrayy 
# cannot append an array!! .append() is only for list

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [53]:
x = [1,2,3]
x += [3,4,5]
x

[1, 2, 3, 3, 4, 5]

In [61]:
x = [1,2,3]
x.extend([3,4,55,6,6])
print(x)

y = ["yay","woah","wow"]
# y.append(3,4,5,7) will not work because .append() is only for one argument
y.append([23,4,5])
y

[1, 2, 3, 3, 4, 55, 6, 6]


['yay', 'woah', 'wow', [23, 4, 5]]

# Some loose ends

## 1.5 Tuples

In [38]:
# tuples are immutable, cannot change after defining
a = 1,2,3
a[0] # can access data
a[0] = 9 # redefining does not work

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [42]:
x = [1,2,3]  # dont just use equal sign!!!
y = x        # lists are mutable
z = x        # can freely change list without changing ID
             # so if i modify/giving another name
             # everything under this same id x,y,z will be changed

y = x.copy() # assigning new ID
z = x.copy() # so that when i modify eg. y, x and z do not change

[1, 2, 3]