<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

Types of data
- list
- numpy array
- tuples
- dataframes
- classes

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [6]:
python_super_names = ["Black Widow","Iron Man","Doctor Strange"]
python_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
print(python_super_names)
print(python_real_names)

['Black Widow', 'Iron Man', 'Doctor Strange']
['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']


In [3]:
np_super_names = np.array(["Black Widow","Iron Man","Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
print(np_super_names)
print(np_real_names)

['Black Widow' 'Iron Man' 'Doctor Strange']
['Natasha Romanoff' 'Tony Stark' 'Stephen Strange']


In [7]:
superhero_info = {
    "Natasha Romanoff":"Black Widow",
    "Tony Stark":"Iron Man",
    "Stephen Strange":"Doctor Strange"
}

# lists refer to Python lists
# arrays refer to numPy arrays, need to 
# import numpy as np, then np.array

## 1.2 Accessing data from a list (or array)

In [8]:
# In python, 0 is the first element

python_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
python_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
python_real_names[2]

'Stephen Strange'

In [14]:
# forward indexing requires us to know size of list before

In [15]:
python_super_names[-1]

'Doctor Strange'

In [16]:
# reverse indexing allows us to get last elements without knowing size

## 1.3 Accessing data from a dictionary

In [17]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}             

superhero_info["Natasha Romanoff"]

'Black Widow'

In [26]:
superhero_info["Doctor Strange"]

# will not work, cannot ask python what is the key for this value
# only can ask python what is the value of this key
# dictionary is key:value structure

KeyError: 'Doctor Strange'

In [27]:
print(superhero_info.keys())

# .keys() to find keys

print(superhero_info.values())

# .values() to find values


dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


## 1.4 Higher dimensional lists

In [41]:
# In dictionary, we can store key:value easily
# However for lists, we need to separate each key:value 
# as its own list with []

py_superhero = [['Natasha Romanoff', 'Black Widow'],
               ['Tony Stark','Iron Man'],
               ['Stephen Strange','Doctor Strange']]
print(py_superhero)
print(py_superhero[2])    # gives the THIRD!! element,
                          # which itself is a list 
print(py_superhero[2][0])

listt = [[[["hi"]]]]
listt[0][0][0][0]    # remember python first element index is 0

[['Natasha Romanoff', 'Black Widow'], ['Tony Stark', 'Iron Man'], ['Stephen Strange', 'Doctor Strange']]
['Stephen Strange', 'Doctor Strange']
Stephen Strange


'hi'

# 2 Lists vs. Arrays

## 2.1 Size

In [50]:
numberlist = [[1,"A"],
             [2,"B"],
             [3,"C"],
             [4,"D"]
             ]

numberarray = np.array(numberlist)
print(numberarray)
print(numberlist)

# after printing out, notice difference in format

print(len(numberlist)) # len() tells u there are 4 elements in this list
print(len(numberarray))
print(numberarray.shape)

# .shape tells you 'shape' of array, 4 row by 2 column
# no such thing for list as list is just one row

# the .shape or .keys .values is not function, 
# is simply calling out python
# to give u the attirbute of the array/dict/list

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']]
[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D']]
4
4
(4, 2)


## 2.2 Arrays are fussy about type

In [51]:
# data types
# int, float, str
# Array can only have ONE data type

In [101]:
listexample = [1,2, 'hehe']
print(listexample)

arrayexample = np.array(listexample)
print(arrayexample)

# as long as there is ONE string, everyth gets converted 
# to string in python array

[1, 2, 'hehe']
['1' '2' 'hehe']


## 2.3 Adding a number

In [54]:
simplelist = [1,2,3]
simplearray = np.array(simplelist) # using list to create array
                                   # can do manually
                                   # but remember ([])

simplelist + 10 # will not work
simplearray + 10 # notice that since the prev line doesnt work
                 # python will not run the next line

TypeError: can only concatenate list (not "int") to list

In [56]:
simplearray + 10     # +10 to each element

array([11, 12, 13])

## 2.4 Adding another list

In [59]:
# however, u can add a list to another list
# to make one longgg list

simplelist = [1,2,3,4,5]
ssecondlist = [2,3,4,5,]

simplelist + ssecondlist 

[1, 2, 3, 4, 5, 2, 3, 4, 5]

In [61]:
# u can also add arrays

simplearray = np.array(simplelist)
ssecondarray = np.array(ssecondlist)

simplearray + ssecondarray
# will not work because the length is not equal

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [62]:
thirdarray = np.array([3,4,5,5,5])
simplearray + thirdarray


array([ 4,  6,  8,  9, 10])

## 2.5 Multiplying by a Number

In [ ]:
simplelist = [1,2,3,4,5]
simplearray = np.array(simplelist)

In [64]:
simplelist*2

# the entire list repeats twice
# multiplying makes list grow

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [65]:
simplearray*2

# different, x2 to each element in array

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [69]:
simplelist = [1,2,3,4,5]
simplearray = np.array(simplelist)

In [70]:
simplelist**2  # will not work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [71]:
simplearray **2 # square each element

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [89]:
simplelist = [1,2,3,4,5]
simplearray = np.array(simplelist)

In [100]:
simplelist == 0,1,2,3,4

(False, 1, 2, 3, 4)

In [91]:
simplelist > 3 # will not work as a list cannot be more than number


TypeError: '>' not supported between instances of 'list' and 'int'

In [92]:
# now for arrays,
# can check if any element in the number is that number

simplearray == 3

array([False, False,  True, False, False])

In [93]:
simplearray > 2

array([False, False,  True,  True,  True])

## 2.8 Mathematics

In [94]:
simplelist = [1,2,3,4,5]
simplearray = np.array(simplelist)

In [95]:
sum(simplelist) # can take sum of list

15

In [102]:
max(simplelist)

5

In [103]:
min(simplelist)

1

In [ ]:
simplelist.sum() # will not work,, this is only for array

In [ ]:
# .sum(), .max(), .min(), .mean(), .std() for array

In [104]:
sum(simplearray) # the 'normal' sum() functions will work too

15

In [105]:
simplearray.sum()

15

In [106]:
min(simplearray)

1

In [108]:
print(simplearray.min())
print(simplearray.max())
print(simplearray.mean())
print(simplearray.std()) # for standard dev of array

1
5
3.0
1.4142135623730951


# Exercises & Self-Assessment

In [ ]:



# Your solution here


